version: '3.8'

services:
  # アプリサーバ
  php:
    build: ./php
    ports:
      - "8080:8080"
    volumes:
      - ./php/html:/var/www/html # php ファイルを記述する場所
      - ./php/scripts:/scripts # bash ファイルを記述する場所
      - ./php/crontab:/etc/cron.d/my-cron # cron の設定ファイルを配置
      - ./.env:/etc/.env # cron が使う環境変数を配置
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    command: php -S 0.0.0.0:8080 -t /var/www/html # PHP組み込みWebサーバを起動

  # データベース
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql # DBを初期化するSQL文を配置

  # データベースを GUI で操作するツール
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql
