version: '3.8'

services:

  # Webサーバ
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # 設定ファイル
      - ./nginx/logs/access.log:/var/log/nginx/access.log # アクセスログ
      - ./nginx/logs/error.log:/var/log/nginx/error.log # エラーログ
    depends_on:
      - mysql

  # アプリサーバ
  php:
    build: ./php
    volumes:
      - ./php/html:/var/www/html # php ファイルを記述する場所
      - ./php/scripts:/scripts # bash ファイルを記述する場所
      - ./php/crontab:/etc/cron.d/my-cron # cron の設定ファイルを配置
      - ./php/.env:/etc/.env # cron が使う環境変数を配置
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  # データベース
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d # sql ファイルや bash ファイル等を記述する場所（コンテナ起動時に自動実行される）

  # データベースを GUI で操作するツール
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql
